### ISSUE TITLE
authenticationToken is not recognized

### ISSUE THREAD

**Issue by coolo19** [gbro115/homebridge-ewelink#2]
I have the issue that mý authToken is not being recognized...

Tried several different methodes, checked the code but somewhere the linking between the plugin and the config seems to fail.

Here is the Failure message:
```
Load homebridge-eWeLink.eWeLink
[2017-12-26 05:58:12] [homebridge-eWeLink.eWeLink] Intialising eWeLink
/usr/local/lib/node_modules/homebridge-ewelink/index.js:42
    this.authenticationToken = config['authenticationToken'];
                                     ^

TypeError: Cannot read property 'authenticationToken' of null
    at new eWeLink (/usr/local/lib/node_modules/homebridge-ewelink/index.js:42:3             8)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/             server.js:325:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:87:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge             :17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

```
and here is my config:

```
	"platforms": [{
			
		"platform": "eWeLink",
		"name": "eWeLink",
		"autheticationToken": "authToken is in here!",
		"apiHost": "eu-api.coolkit.cc:8080/api/group?apikey=apikeygoeshere&appid=xyz&nonce=eto149q7&ts=1514263532&version=6",
		"webSocketApi": "eu-api.coolkit.cc:8080/api/group?apikey=apikeygoeshere&appid=xyz&ts=1514263532&version=6"
		},
			]
}
```
greetings from Germany 

Kevin

**Comment by gbro115** [comment]
One thing that I can see in your config is that the URL keys are not set correctly; you only need the hostname component: eu-api.coolkit.cc.

Are you able to show the logs from the start of the launch?

George

Sent from my mobile device
_____________________________

**Comment by gbro115** [comment]
So I lied... the apiHost does need the port number as well, but nothing after it. 

The webSocketHost only needs the hostname.

**Comment by coolo19** [comment]
Okay, i‘ll try it later and give you Feedback If it worked. 😅

**Comment by coolo19** [comment]
okay, just tried it. Thought i found the error because i had a typo in my config.

After correcting it it at least now shows it in my Home app.

But it still fails with the same error as you can see below:

this is from Start:
```

pi@raspberrypi:~ $ sudo homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2017-12-26 23:06:24] Loaded plugin: homebridge-ewelink
homebridge API version: 2.2
[2017-12-26 23:06:24] Registering platform 'homebridge-eWeLink.eWeLink'
[2017-12-26 23:06:24] ---
[2017-12-26 23:06:24] Loaded plugin: homebridge-harmonyhub
[2017-12-26 23:06:27] Registering platform 'homebridge-harmonyhub.HarmonyHub'
[2017-12-26 23:06:27] ---
[2017-12-26 23:06:28] Loaded plugin: homebridge-tplink-smarthome
[2017-12-26 23:06:28] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
[2017-12-26 23:06:28] ---
[2017-12-26 23:06:28] Loaded plugin: homebridge-wol
[2017-12-26 23:06:28] Registering accessory 'homebridge-wol.NetworkDevice'
[2017-12-26 23:06:28] ---
[2017-12-26 23:06:28] config.json (/root/.homebridge/config.json) not found.
Load homebridge-eWeLink.eWeLink
[2017-12-26 23:06:28] [homebridge-eWeLink.eWeLink] Intialising eWeLink
/usr/local/lib/node_modules/homebridge-ewelink/index.js:42
    this.authenticationToken = config['authenticationToken'];
                                     ^

TypeError: Cannot read property 'authenticationToken' of null
    at new eWeLink (/usr/local/lib/node_modules/homebridge-ewelink/index.js:42:38)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:325:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:87:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
pi@raspberrypi:~ $

```

**Comment by coolo19** [comment]
maybe youll find the issue 
here is my config: 
```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-545"
	},

	"accessoires": [{
		"accessory": "NetworkDevice",
		"name": "Büro PC",
		"mac": "xx:xx:xx:xx:xx",
		"ip": "192.168.115.11",
		"pingInterval": 45,
		"wakeGraceTime": 90,
		"shutdownGraceTime": 15,
		"shutdownCommand": "sfewfeveeegf"
	}],

	"platforms": [{
			"platform": "TplinkSmarthome",
			"name": "TplinkSmarthome"

		},
		{
			"platform": "eWeLink",
			"name": "eWeLink",
			"authenticationToken": "d4300083ce65527b882775750d2794c6a9453ea6",
			"apiHost": "eu-api.coolkit.cc:8080",
			"webSocketApi": "eu-api.coolkit.cc"
		},
		{
			"platform": "HarmonyHub",
			"name": "Harmony Hub Kev"
		}
	]
}
```

**Comment by gbro115** [comment]
Are you sure that it’s reading your config file correctly?

This makes me suspicious that it isn’t:

[2017-12-26 23:06:28] config.json (/root/.homebridge/config.json) not found.

If it can’t find the file, then all the config values will be null, which would explain the error

Sent from my mobile device
________________________________

**Comment by coolo19** [comment]
Hey,

the issue with config not found is from the wol Plugin because it Needs to run in Root But thats not the Problem, because all other Plugins in the Same config are Running without Root in /Home/pi/.homebridge/config.json... 
i think the issue is that the Plugin Cannot recognize the authenticationToken variable in my config:
‘‘‘
TypeError: Cannot read property 'authenticationToken' of null
    at new eWeLink ...
‘‘‘

**Comment by gbro115** [comment]
@coolo19 I'm travelling at the moment, but I'll try to take a look at this over the coming weeks. I am thinking that it is something to do with your config file not being found

```
[2017-12-26 23:06:28] [homebridge-eWeLink.eWeLink] Intialising eWeLink
/usr/local/lib/node_modules/homebridge-ewelink/index.js:42
    this.authenticationToken = config['authenticationToken'];
                                     ^

TypeError: Cannot read property 'authenticationToken' of null
```

The config variable is null.

**Comment by EmmaMay66** [comment]
hi, so i think im having the same issue.. just to explain im totally new to all this homebridge stuff and all this programming stuff so please explain as simply as you can... i can pick thing sup pretty quickly and i do know some things. and this is my first device i am trying to set up... 

this is the error im getting in CMD:

C:\Users\louis>homebridge
[2018-4-15 18:44:43] Loaded plugin: homebridge-ewelink
homebridge API version: 2.2
[2018-4-15 18:44:43] Registering platform 'homebridge-eWeLink.eWeLink'
[2018-4-15 18:44:43] ---
[2018-4-15 18:44:43] Loaded plugin: homebridge-http
[2018-4-15 18:44:43] Registering accessory 'homebridge-http.Http'
[2018-4-15 18:44:43] ---
[2018-4-15 18:44:43] config.json (C:\Users\louis\.homebridge\config.json) not found.
Load homebridge-eWeLink.eWeLink
[2018-4-15 18:44:43] [homebridge-eWeLink.eWeLink] Intialising eWeLink
C:\Users\louis\AppData\Roaming\npm\node_modules\homebridge-ewelink\index.js:42
    this.authenticationToken = config['authenticationToken'];
                                     ^

TypeError: Cannot read property 'authenticationToken' of null
    at new eWeLink (C:\Users\louis\AppData\Roaming\npm\node_modules\homebridge-ewelink\index.js:42:38)
    at Server._loadDynamicPlatforms (C:\Users\louis\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:325:30)
    at Server.run (C:\Users\louis\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:87:8)
    at module.exports (C:\Users\louis\AppData\Roaming\npm\node_modules\homebridge\lib\cli.js:40:10)
    at Object.<anonymous> (C:\Users\louis\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

and this is my config file.    location: C:\Users\louis\AppData\Roaming\npm\node_modules\homebridge

{ 
"Bridge": { 
"name": "HomeBridge", 
"username": "CC: 22: 3D: E3: CE: 30", 
"Port": 51826, 
"Pin": "031-45-154" 
} ,

"Description": "HomeBridge HTTP Status Control"

"accessories": [
    ],

    "platforms": [
        {
        "platform" : "eWeLink",
        "name" : "eWeLink",
        "authenticationToken" : "bearer5fe476165d0e22740d2623d4223954e030bae4da",
        "apiHost" : "us-api.coolkit.cc:8080",
        "webSocketApi" : "us-api.coolkit.cc"
        }
    ]
}




please help... its driving me insane, that i have got this far and im stuck...

**Comment by MrTomAsh** [comment]
@EmmaMay66 I have no experience with running homebridge on a Windows machine, but from what I can see your problem isn't the config.json file but wrong interpretation of JS. In your case "this" can't be found. Speaking very simple - "this" it's a script itself.

I think you should check you npm version and install everything from scratch. Also, check if other plugins work correctly.

**Comment by EmmaMay66** [comment]
Okay. I will try that tonight. 
But npm version? 
How do I check that? And what should it be?

**Comment by MrTomAsh** [comment]
@EmmaMay66 
`npm -version`

**Comment by sapidog** [comment]
@EmmaMay66  I just keep eWeLink platform and working fine .(remove "platform": "TplinkSmarthome",...etc)

**Comment by tacion01** [comment]
@MrTomAsh what should the npm version be?

**Comment by ukxxx** [comment]
Guys just try to copy your 'config.json' to the place home bridge want to.
sudo cp /usr/local/lib/node_modules/homebridge/config1.json /home/pi/.homebridge/config.json

**Comment by MrBrodi** [comment]
Same Problem here. 
TypeError: Cannot read property 'authenticationToken' of null ...

my config.json:

{                                                                                                                       
    "bridge": {                                                                                                         
        "name": "Homebridge",                                                                                           
        "username": "**:**:**:**:**:**",                                                                                
        "port": 51826,                                                                                                  
        "pin": "031-45-154"                                                                                             
    },                                                                                                                  
                                                                                                                        
    "description": "This is an example configuration file. You can use this as a template for creating your own configur
                                                                                                                        
    "accessories": [                                                                                                    
    ],                                                                                                                  
                                                                                                                        
    "platforms": [                                                                                                      
        {                                                                                                               
        "platform" : "eWeLink",                                                                                         
        "name" : "eWeLink",                                                                                             
        "authenticationToken" : "8f******************************************",                                             
        "apiHost" : "eu-api.coolkit.cc:8080",                                                                           
        "webSocketApi" : "eu-pconnect3.coolkit.cc"                                                                      
        }                                                                                                               
    ]                                                                                                                   
}     


Is the problem fixed in the meantime?

**Comment by MrBrodi** [comment]
2 Minutes later i have found the issue. 💃 

Just copied config.json from /homebridge to /.homebridge
Now its working

Command:
cp config.json /root/.homebridge
